
import type { AssessmentWithResults, EngineResult } from '@/types'

export async function generateAssessmentPDF(
  assessment: AssessmentWithResults,
  userName: string,
  userBloodType: string | null
): Promise<void> {
  const { jsPDF } = await import('jspdf')
  const html2canvas = (await import('html2canvas')).default

  const today = new Date().toISOString().split('T')[0]
  const patientId = `MS-${assessment.id.slice(-5).toUpperCase()}`

  const engineResults: EngineResult[] = assessment.engineResults ?? []

  const container = document.createElement('div')
  container.style.cssText = `
    position: fixed;
    top: -9999px;
    left: -9999px;
    width: 900px;
    background: #ffffff;
    color: #1a1a2e;
    font-family: 'Inter', Arial, sans-serif;
    font-size: 13px;
    padding: 48px;
    box-sizing: border-box;
  `

  const getRiskColor = (level: string | null): string => {
    switch (level) {
      case 'LOW':      return '#16a34a'
      case 'MEDIUM':   return '#ca8a04'
      case 'HIGH':     return '#dc2626'
      case 'CRITICAL': return '#7f1d1d'
      default:         return '#6b7280'
    }
  }

  // const formatRisk = (risk: number | null, level: string | null): string => {
  //   if (risk == null) return 'N/A'
  //   return `${risk}% — ${level ?? 'N/A'}`
  // }

  const diseases = [
    { label: 'Diabetes',      risk: assessment.diabetesRisk,      level: assessment.diabetesLevel,      conf: engineResults.find(e => e.isBest)?.diseases.diabetes.confidence },
    { label: 'Heart Disease', risk: assessment.heartDiseaseRisk,  level: assessment.heartDiseaseLevel,  conf: engineResults.find(e => e.isBest)?.diseases.heartDisease.confidence },
    { label: 'Hypertension',  risk: assessment.hypertensionRisk,  level: assessment.hypertensionLevel,  conf: engineResults.find(e => e.isBest)?.diseases.hypertension.confidence },
    { label: 'Stroke',        risk: assessment.strokeRisk,        level: assessment.strokeLevel,        conf: engineResults.find(e => e.isBest)?.diseases.stroke.confidence },
    { label: 'Kidney Disease',risk: assessment.kidneyDiseaseRisk, level: assessment.kidneyDiseaseLevel, conf: engineResults.find(e => e.isBest)?.diseases.kidneyDisease.confidence },
    { label: 'Liver Disease', risk: assessment.liverDiseaseRisk,  level: assessment.liverDiseaseLevel,  conf: engineResults.find(e => e.isBest)?.diseases.liverDisease.confidence },
  ]

  container.innerHTML = `
    <!-- ── HEADER ────────────────────────────────────────────────────────── -->
    <div style="display:flex;align-items:center;justify-content:space-between;padding-bottom:24px;border-bottom:3px solid #00363a;margin-bottom:32px;">
      <div>
        <div style="font-size:28px;font-weight:800;color:#00363a;letter-spacing:-0.5px;">MediSense AI</div>
        <div style="font-size:12px;color:#374151;margin-top:2px;letter-spacing:2px;text-transform:uppercase;">Clinical Intelligence Report</div>
      </div>
      <div style="text-align:right;">
        <div style="font-size:11px;color:#6b7280;">Report Date: ${today}</div>
        <div style="font-size:11px;color:#6b7280;">Patient ID: ${patientId}</div>
        <div style="font-size:11px;color:#6b7280;">Generated by MediSense AI v3</div>
      </div>
    </div>

    <!-- ── PATIENT INFO ──────────────────────────────────────────────────── -->
    <div style="margin-bottom:32px;">
      <div style="font-size:15px;font-weight:700;color:#00363a;margin-bottom:12px;text-transform:uppercase;letter-spacing:1px;">Patient Information</div>
      <table style="width:100%;border-collapse:collapse;font-size:13px;">
        <tr style="background:#f0fdf4;">
          <td style="padding:8px 12px;font-weight:600;width:25%;border:1px solid #d1fae5;">Full Name</td>
          <td style="padding:8px 12px;border:1px solid #d1fae5;">${userName}</td>
          <td style="padding:8px 12px;font-weight:600;width:25%;border:1px solid #d1fae5;">Patient ID</td>
          <td style="padding:8px 12px;border:1px solid #d1fae5;">${patientId}</td>
        </tr>
        <tr>
          <td style="padding:8px 12px;font-weight:600;border:1px solid #d1fae5;">Age</td>
          <td style="padding:8px 12px;border:1px solid #d1fae5;">${assessment.age} years</td>
          <td style="padding:8px 12px;font-weight:600;border:1px solid #d1fae5;">Gender</td>
          <td style="padding:8px 12px;border:1px solid #d1fae5;">${assessment.gender}</td>
        </tr>
        <tr style="background:#f0fdf4;">
          <td style="padding:8px 12px;font-weight:600;border:1px solid #d1fae5;">BMI</td>
          <td style="padding:8px 12px;border:1px solid #d1fae5;">${assessment.bmi.toFixed(1)} kg/m²</td>
          <td style="padding:8px 12px;font-weight:600;border:1px solid #d1fae5;">Blood Type</td>
          <td style="padding:8px 12px;border:1px solid #d1fae5;">${userBloodType ?? 'Not set'}</td>
        </tr>
        <tr>
          <td style="padding:8px 12px;font-weight:600;border:1px solid #d1fae5;">Weight</td>
          <td style="padding:8px 12px;border:1px solid #d1fae5;">${assessment.weight} kg</td>
          <td style="padding:8px 12px;font-weight:600;border:1px solid #d1fae5;">Height</td>
          <td style="padding:8px 12px;border:1px solid #d1fae5;">${assessment.height} cm</td>
        </tr>
        <tr style="background:#f0fdf4;">
          <td style="padding:8px 12px;font-weight:600;border:1px solid #d1fae5;">Assessment Date</td>
          <td style="padding:8px 12px;border:1px solid #d1fae5;">${new Date(assessment.createdAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</td>
          <td style="padding:8px 12px;font-weight:600;border:1px solid #d1fae5;">Analysis Engine</td>
          <td style="padding:8px 12px;border:1px solid #d1fae5;">${assessment.bestEngine ?? 'Neural Network'}</td>
        </tr>
      </table>
    </div>

    <!-- ── OVERALL HEALTH INDEX ──────────────────────────────────────────── -->
    <div style="margin-bottom:32px;padding:20px;background:#f0fdf4;border:2px solid #bbf7d0;border-radius:8px;display:flex;align-items:center;gap:24px;">
      <div style="text-align:center;min-width:100px;">
        <div style="font-size:48px;font-weight:800;color:#00363a;line-height:1;">${assessment.overallHealthIndex ?? '—'}</div>
        <div style="font-size:11px;color:#374151;text-transform:uppercase;letter-spacing:1px;">/ 100</div>
      </div>
      <div>
        <div style="font-size:16px;font-weight:700;color:#00363a;">Overall Health Index</div>
        <div style="font-size:13px;color:#374151;margin-top:4px;">
          Urgency Level: <strong style="color:${assessment.urgency === 'URGENT' || assessment.urgency === 'SOON' ? '#dc2626' : '#16a34a'};">${assessment.urgency ?? 'N/A'}</strong>
        </div>
        <div style="font-size:12px;color:#6b7280;margin-top:4px;">${assessment.urgencyText ?? ''}</div>
      </div>
    </div>

    <!-- ── DISEASE RISK TABLE ─────────────────────────────────────────────── -->
    <div style="margin-bottom:32px;">
      <div style="font-size:15px;font-weight:700;color:#00363a;margin-bottom:12px;text-transform:uppercase;letter-spacing:1px;">Disease Risk Predictions</div>
      <table style="width:100%;border-collapse:collapse;font-size:13px;">
        <thead>
          <tr style="background:#00363a;color:#ffffff;">
            <th style="padding:10px 12px;text-align:left;font-weight:600;">Disease</th>
            <th style="padding:10px 12px;text-align:center;font-weight:600;">Risk Score</th>
            <th style="padding:10px 12px;text-align:center;font-weight:600;">Risk Level</th>
            <th style="padding:10px 12px;text-align:center;font-weight:600;">Confidence</th>
          </tr>
        </thead>
        <tbody>
          ${diseases.map((d, i) => `
            <tr style="background:${i % 2 === 0 ? '#f9fafb' : '#ffffff'};">
              <td style="padding:9px 12px;font-weight:500;border:1px solid #e5e7eb;">${d.label}</td>
              <td style="padding:9px 12px;text-align:center;border:1px solid #e5e7eb;font-weight:700;color:${getRiskColor(d.level)};">${d.risk != null ? `${d.risk}%` : 'N/A'}</td>
              <td style="padding:9px 12px;text-align:center;border:1px solid #e5e7eb;">
                <span style="background:${getRiskColor(d.level)}20;color:${getRiskColor(d.level)};padding:2px 10px;border-radius:9999px;font-size:11px;font-weight:700;">${d.level ?? 'N/A'}</span>
              </td>
              <td style="padding:9px 12px;text-align:center;border:1px solid #e5e7eb;color:#6b7280;">${d.conf != null ? `${d.conf.toFixed(1)}%` : 'N/A'}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    </div>

    <!-- ── ENGINE COMPARISON SUMMARY ─────────────────────────────────────── -->
    <div style="margin-bottom:32px;">
      <div style="font-size:15px;font-weight:700;color:#00363a;margin-bottom:12px;text-transform:uppercase;letter-spacing:1px;">Engine Comparison Summary (All 10 Models)</div>
      <table style="width:100%;border-collapse:collapse;font-size:12px;">
        <thead>
          <tr style="background:#00363a;color:#ffffff;">
            <th style="padding:8px 10px;text-align:left;font-weight:600;">Engine</th>
            <th style="padding:8px 10px;text-align:center;font-weight:600;">Accuracy</th>
            <th style="padding:8px 10px;text-align:center;font-weight:600;">Diabetes</th>
            <th style="padding:8px 10px;text-align:center;font-weight:600;">Heart</th>
            <th style="padding:8px 10px;text-align:center;font-weight:600;">Hypertension</th>
            <th style="padding:8px 10px;text-align:center;font-weight:600;">Stroke</th>
            <th style="padding:8px 10px;text-align:center;font-weight:600;">Inference</th>
          </tr>
        </thead>
        <tbody>
          ${engineResults.length > 0 ? engineResults.map((e, i) => `
            <tr style="background:${e.isBest ? '#f0fdf4' : i % 2 === 0 ? '#f9fafb' : '#ffffff'};">
              <td style="padding:7px 10px;font-weight:${e.isBest ? '700' : '400'};border:1px solid #e5e7eb;color:${e.isBest ? '#00363a' : 'inherit'};">
                ${e.isBest ? '★ ' : ''}${e.engine}
              </td>
              <td style="padding:7px 10px;text-align:center;border:1px solid #e5e7eb;">${e.accuracy}%</td>
              <td style="padding:7px 10px;text-align:center;border:1px solid #e5e7eb;color:${getRiskColor(e.diseases.diabetes.level)};">${e.diseases.diabetes.risk}%</td>
              <td style="padding:7px 10px;text-align:center;border:1px solid #e5e7eb;color:${getRiskColor(e.diseases.heartDisease.level)};">${e.diseases.heartDisease.risk}%</td>
              <td style="padding:7px 10px;text-align:center;border:1px solid #e5e7eb;color:${getRiskColor(e.diseases.hypertension.level)};">${e.diseases.hypertension.risk}%</td>
              <td style="padding:7px 10px;text-align:center;border:1px solid #e5e7eb;color:${getRiskColor(e.diseases.stroke.level)};">${e.diseases.stroke.risk}%</td>
              <td style="padding:7px 10px;text-align:center;border:1px solid #e5e7eb;color:#6b7280;">${e.inferenceMs}ms</td>
            </tr>
          `).join('') : `
            <tr><td colspan="7" style="padding:16px;text-align:center;color:#6b7280;border:1px solid #e5e7eb;">No engine data available</td></tr>
          `}
        </tbody>
      </table>
    </div>

    <!-- ── KEY FACTORS ────────────────────────────────────────────────────── -->
    ${assessment.keyFactors && assessment.keyFactors.length > 0 ? `
    <div style="margin-bottom:32px;">
      <div style="font-size:15px;font-weight:700;color:#00363a;margin-bottom:12px;text-transform:uppercase;letter-spacing:1px;">Key Clinical Factors</div>
      <ul style="margin:0;padding-left:20px;">
        ${assessment.keyFactors.map(f => `<li style="padding:4px 0;color:#374151;">${f}</li>`).join('')}
      </ul>
    </div>
    ` : ''}

    <!-- ── RECOMMENDATIONS ────────────────────────────────────────────────── -->
    ${assessment.recommendations ? `
    <div style="margin-bottom:32px;">
      <div style="font-size:15px;font-weight:700;color:#00363a;margin-bottom:12px;text-transform:uppercase;letter-spacing:1px;">Clinical Recommendations</div>
      
      ${assessment.recommendations.directive ? `
      <div style="padding:16px;background:#fef9c3;border:1px solid #fde047;border-radius:8px;margin-bottom:16px;">
        <div style="font-weight:700;font-size:14px;color:#713f12;">${assessment.recommendations.directive.title}</div>
        <div style="color:#78350f;margin-top:4px;font-size:13px;">${assessment.recommendations.directive.description}</div>
        <div style="color:#92400e;margin-top:4px;font-size:12px;">Risk Score: ${assessment.recommendations.directive.riskScore}/10</div>
      </div>
      ` : ''}

      ${assessment.recommendations.medications && assessment.recommendations.medications.length > 0 ? `
      <div style="margin-bottom:16px;">
        <div style="font-weight:600;margin-bottom:8px;color:#374151;">Medication Protocol:</div>
        <table style="width:100%;border-collapse:collapse;font-size:12px;">
          <thead>
            <tr style="background:#f3f4f6;">
              <th style="padding:7px 10px;text-align:left;border:1px solid #e5e7eb;">Medication</th>
              <th style="padding:7px 10px;text-align:left;border:1px solid #e5e7eb;">Dosage</th>
              <th style="padding:7px 10px;text-align:center;border:1px solid #e5e7eb;">Action</th>
            </tr>
          </thead>
          <tbody>
            ${assessment.recommendations.medications.map(m => `
              <tr>
                <td style="padding:7px 10px;border:1px solid #e5e7eb;">${m.name}</td>
                <td style="padding:7px 10px;border:1px solid #e5e7eb;color:#6b7280;">${m.dose}</td>
                <td style="padding:7px 10px;text-align:center;border:1px solid #e5e7eb;">
                  <span style="background:${m.action === 'ADD' ? '#dcfce7' : m.action === 'ADJUST' ? '#fef3c7' : '#f3f4f6'};color:${m.action === 'ADD' ? '#166534' : m.action === 'ADJUST' ? '#92400e' : '#374151'};padding:2px 8px;border-radius:4px;font-size:11px;font-weight:600;">${m.action}</span>
                </td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      </div>
      ` : ''}

      ${assessment.recommendations.carePathway && assessment.recommendations.carePathway.length > 0 ? `
      <div>
        <div style="font-weight:600;margin-bottom:8px;color:#374151;">Care Pathway:</div>
        ${assessment.recommendations.carePathway.map(c => `
          <div style="padding:8px 12px;border-left:3px solid #00363a;margin-bottom:8px;background:#f9fafb;">
            <div style="font-weight:600;font-size:12px;color:#00363a;">${c.type}</div>
            <div style="font-size:11px;color:#6b7280;">${new Date(c.date).toLocaleDateString()} — ${c.notes}</div>
          </div>
        `).join('')}
      </div>
      ` : ''}
    </div>
    ` : ''}

    <!-- ── CLINICAL INSIGHT ───────────────────────────────────────────────── -->
    ${assessment.clinicalInsight ? `
    <div style="margin-bottom:32px;padding:16px;background:#eff6ff;border:1px solid #bfdbfe;border-radius:8px;">
      <div style="font-size:13px;font-weight:700;color:#1e40af;margin-bottom:6px;text-transform:uppercase;letter-spacing:1px;">Clinical Insight</div>
      <div style="color:#1e3a8a;font-size:13px;line-height:1.6;">${assessment.clinicalInsight}</div>
    </div>
    ` : ''}

    <!-- ── FOOTER ─────────────────────────────────────────────────────────── -->
    <div style="border-top:2px solid #e5e7eb;padding-top:16px;margin-top:8px;display:flex;justify-content:space-between;align-items:center;">
      <div style="font-size:11px;color:#9ca3af;">
        <strong style="color:#374151;">DISCLAIMER:</strong> This report is generated by AI and is for informational purposes only. It does not constitute medical advice. Consult a licensed healthcare professional before making any medical decisions.
      </div>
      <div style="font-size:11px;color:#9ca3af;text-align:right;min-width:140px;">
        MediSense AI v3<br/>
        ${today}
      </div>
    </div>
  `

  document.body.appendChild(container)

  try {
    const canvas = await html2canvas(container, {
      scale: 2,
      useCORS: true,
      backgroundColor: '#ffffff',
      logging: false,
      width: 900,
    })

    const imgData = canvas.toDataURL('image/png')
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'px',
      format: 'a4',
    })

    const pdfWidth  = pdf.internal.pageSize.getWidth()
    const pdfHeight = pdf.internal.pageSize.getHeight()
    const imgWidth  = canvas.width
    const imgHeight = canvas.height
    const ratio     = pdfWidth / imgWidth
    const scaledH   = imgHeight * ratio

    let position = 0
    let remaining = scaledH

    pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, scaledH)

    while (remaining > pdfHeight) {
      position -= pdfHeight
      remaining -= pdfHeight
      pdf.addPage()
      pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, scaledH)
    }

    pdf.save(`MediSense-Report-${today}.pdf`)
  } finally {
    document.body.removeChild(container)
  }
}